spring:
  mail:
    host: smtp.163.com
    username: 18035235885@163.com
    password: EHj7hzEHdhy7s4p5
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          from: 18035235885@163.com
  application:
    name: MapApp
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    timeout: 2592000
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/MapApp
    username: root
    password: root
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      # 设置监听容器（Listener container）类型，如不设置，将会默认为SimpleRabbitListenerContainerFactory，且下面的direct配置不生效
      type: direct
      direct:
        acknowledge-mode: manual # 手动ACK开启：自动确认 none ;手动确认 manual ;根据异常情况确认 auto (较麻烦，不推荐)
  # Redis 配置
  redis:
    database: 1
    host: localhost
    password: 123456
    port: 6379
    timeout: 5000
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
  # 对象存储
aliyun:
   oss:
     endpoint: ${aliyun.oss.endpoint}
     accessKeyId: ${aliyun.oss.accessKeyId}
     accessKeySecret: ${aliyun.oss.accessKeySecret}
     bucketName: ${aliyun.oss.bucketName}

server:
  address: 0.0.0.0
  port: 8001
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
jwt:
    secret: asdfghjkl
    expire-time: 604800000